name: Daily Code Execution

on:
  schedule:
    # Run every day at 00:00 UTC
    - cron: '0 0 * * *'
  push:
    # Optionally specify branches if needed
    branches:
      - main  # Change 'master' to the default branch of your repository if it's different

jobs:
  execute-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies for Google API
        run: |
          pip install -r requirements.txt

      - name: Execute script
        run: |
          bash script/main.sh # Run the script

      - name: Configure Git
        run: |
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.EMAIL }}

      - name: Add changes to git
        run: |
          git add ./outputs

      - name: Commit changes
        run: |
          git commit -m "Daily Code Execution GitHub Action" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push origin main